### ISSUE TITLE
Create a Vagrantfile for local development and test

### ISSUE THREAD

**Issue by Ranjandas** [DigitalEarns/upswing#1]
We will be using Vagrant for all our local development and test purpose. Vagrantfile will require multi-machine configuration with a suitable IP range. The basebox should be the official [CentOS 7 ](https://atlas.hashicorp.com/centos/boxes/7) vagrant image. 4 VM's are planned in the initial stage, this may change going forward.

**Comment by sujeshchirackkal** [comment]
That's good to start with. Should we have sub directories under the repo for vagrant, docker etc. (of course we might have to use relative paths to use them)

**Comment by krishnadasmallya** [comment]
Yet to see any contributions here and wondering how to start. Any pointers?

**Comment by sebinjohn** [comment]
Are you looking for documentation?

**Comment by krishnadasmallya** [comment]
@sebinjohn more specifically a bit more clarity on steps(smaller the better) we are planning to accomplish the whole (picture that @Ranjandas shared in gitter as of now). Given that some one (like me) with no background in platform related tasks cannot start from blank :smile:

**Comment by sebinjohn** [comment]
@krishnadasmallya I think  you can start with vagrant(if you have basic idea about virtualisation).
