### ISSUE TITLE
Which images to use?

### ISSUE THREAD

**Issue by sebinjohn** [DigitalEarns/upswing#15]
Are we going to use the official docker images of different components or build everything from scratch?

**Comment by Ranjandas** [comment]
If there is an Official Image we will use it, if it is something developed by community members we will try to build our own version bringing it closer to our requirements.

**Comment by sebinjohn** [comment]
To be specific; an image created by docker or the product owner?

**Comment by Ranjandas** [comment]
Both. There are official docker images which is a part of docker-library https://github.com/docker-library/official-images. And for images outside that, we will ensure that its created but the organisation/owner of the software. If the available image does not fall under both the category we will create our own. We can use the instructions given here (https://github.com/docker-library/official-images) as the best practice to write Dockerfile till we find a more convincing approach.

**Comment by sebinjohn** [comment]
:+1:
