### ISSUE TITLE
Install and configure Docker with Multi-Host Networking.

### ISSUE THREAD

**Issue by Ranjandas** [DigitalEarns/upswing#2]
We are planning to deploy all our services in the CI/CD pipeline as Docker containers. This will require a stable pool of Docker enabled machines that can seamlessly host docker containers. We will be also giving importance to Docker Multi-Host networking as this will enable containers on different host to talk to each other. As docker now has native multi-host networking capabilities, we are planning to use the same throughout this project.

Install Docker Engine on 4 nodes and enable multi-host networking. Test the connectivity of containers from all the hosts.

**Comment by sebinjohn** [comment]
@Ranjandas shouldn't we work on this issue before others?
