### ISSUE TITLE
Evaluate PCP and Netflix Vector for Monitoring

### ISSUE THREAD

**Issue by Ranjandas** [DigitalEarns/upswing#40]
Looks like Red Hat and Netflix are two major users of PCP. http://pcp.io/. Lets evaluate this for upswing.

**Comment by sebinjohn** [comment]
Are we planning to integrate both or evaluate separately?

**Comment by sebinjohn** [comment]
Vector UI showing PCP metrics
![screen shot 2016-06-06 at 2 02 00 am](https://cloud.githubusercontent.com/assets/7448659/15845658/7808b6f6-2cb8-11e6-927d-c2d9ecc46c4b.png)

**Comment by sebinjohn** [comment]
We can select only one host at a time in Vector. I think it is a disadvantage

**Comment by sebinjohn** [comment]
Close this ?

**Comment by Ranjandas** [comment]
Yes, we can close this for now. We will work on a better monitoring and alerting story for upswing and revisit.
